name: main
channels:
  - conda-forge
  - defaults
dependencies:
  - quartodoc
  - jupyter
  - yaml
  - numpy
  - pandas
  - shiny
  - dash
  - altair
  - conda-lock
  - ipykernel
  - ipywidgets
  - jupyterlab
  - make
  - matplotlib
  - pandoc
  - pandocfilters
  - pip
  - plotly
  - pydantic
  - pytest
  - quarto
  - requests
  - tabulate
  - tinycss2
  - urllib3
  - vegafusion
  - vegafusion-jupyter
  - wheel
