---
title: "Main page"
---

Hello there! I'm Alexander Wen, but just call me Alex. I am currently in the UBC MDS program, and you can expect this website about my work and tangibly related competitive programming antics to be updated in the upcoming months of the 2025 school year. 


## Featured Projects

[cdc_diabetes_prediction](https://github.com/alxwen711/cdc_diabetes_prediction) - Basic data analysis on predicting diabetes based on health and lifestyle features following sound data scientific workflows as part of the main project for DSCI 522 (Data Science Workflows), a course in the Master of Data Science program at the University of British Columbia.

## Competitive Programming Profiles

As a start, here are a series of links to my main competitive programming profiles, ordered roughly in descending order of activity.

[CodeForces](https://codeforces.com/profile/Nolirue_Sola)

[AtCoder](https://atcoder.jp/users/SnowLucario)

[Leetcode](https://leetcode.com/u/alxwen711/)

[CodeChef](https://www.codechef.com/users/snowlucario)


## HonestCode: A Blog About Competitive Programming

This is something I'm planning on actually building up seriously. Pretty much a spot for me to occasionally talk about competitive programming topics, which includes:

- Actual algorithm and data structure explanations
- Contest recaps
- Practice methods
- A divulge of my thoughts on AI in the context of competitive programming that is only slightly less [Um_nik](https://codeforces.com/blog/entry/62730)-like
- Interesting problems

For now though [here is a first post about Sparse Tables](./src/HonestCode/sparsetable.html) to get this started.